<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Terms and Conditions</title>
<style type="text/css">
h1 {
	text-align: center;
}
pre {
	font-size: medium;
	color: blue;
	font-family: sans-serif;
}
b {
	text-align: center;
	font-size: large;
	color: red;
	font-family: cursive;
}
</style>
</head>
<body >
<h1>Terms and conditions</h1>
<div class='Termscontent'>
<pre>
<b>Terms Of Use</b>

PLEASE READ CAREFULLY THESE TERMS OF USE, AS THEY CONSTITUTE A BINDING LEGAL AGREEMENT BETWEEN YOU AND iMonitor Solutions India Private Limited ("iMonitor"), AND GOVERN YOUR USE OF THIS WEBSITE AND THE INTERNET AND APPLICATION SERVICES ACCESSED VIA iMonitor Solutions AND iMonitor Solutions BRANDS. BY USING THE WEBSITE OR SUCH SERVICES, YOU ARE ACCEPTING AND AGREEING TO THESE TERMS ON BEHALF OF YOURSELF OR THE ENTITY YOU REPRESENT, AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ACCEPT AND AGREE TO THESE TERMS ON BEHALF OF YOURSELF OR THE ENTITY YOU REPRESENT. IF YOU DO NOT AGREE WITH THESE TERMS OF USE, YOU MAY NOT ACCESS, REGISTER FOR OR USE THE WEBSITE OR THE SERVICES ACCESSED THROUGH THE WEBSITE.
<b>1. Introduction and Scope</b>
iMonitor Solutions ("iMonitor") sells hardware products (the "Hardware") and software, either embedded in the Hardware or distributed separately (the "Software" and together with the Hardware, the "iMonotor Control System"). iMonitor Solutions owns and operates this website and other websites of iMonitor-owned brands, and provides access to certain internet and software application services related to the use of iMonitor Systems and iMonitor-owned brands (the "Services").
These Terms of Use, together with the iMonitor privacy policy, form a binding legal agreement between you and iMonitor (the "Agreement") that sets forth the terms and conditions under which iMonitor agrees to make the Website and the Services available to you and which govern your use of the Website and the Services provided to you.
iMonitor may, in its sole discretion and without prior notice to you, add, delete or otherwise change the provisions of these Terms by posting on the Website a version of these Terms containing such changes. You should periodically check the Website for the most current version of these Terms. If you are dissatisfied with any such changes to these Terms, your sole recourse will be to cease use of the Website and the Services or any portion thereof, in accordance with Section 10 below.

<b>2. Services</b>
The features and functions of the Services are described in more detail in the applicable iMonitor user documentation and guidelines available elsewhere on the Website. The Services include any additional features and functionality that iMonitor may, in its sole discretion and from time to time, offer to you. iMonitor may, in its sole discretion and without notice to you, add, delete or otherwise change features and functions of the Services at any time. If you are dissatisfied with any such changes to the Services, you may immediately cancel your use of such Services as provided in Section 10 below.

<b>3. Eligibility and Registration</b>
You may subscribe to the Services only if you have the legal capacity to form a binding contract with iMonitor. In particular, if you are under eighteen (18) years of age, you may not register to use the Services, and must have someone in your household who is at least eighteen (18) years of age register to use the Services. You may not use the Services if iMonitor has previously prohibited you from use of the Website and/or the Services.
You are required to register your iMonitor System in order to use the Services. Use of the Services requires that your iMonitor System be connected to an always-on, broadband Internet connection. During the registration process you may be asked to provide certain information (the "User Information") to iMonitor such as: (a) your full name; (b) your mailing address; and (c) your e-mail address, (d)your residential address. You agree to provide accurate and complete User Information during the registration process. 
User Information shall also include any data collected by iMonitor from time to time on the installation, settings and use of your iMonitor System, including information obtained for use in data analytics or software development and maintenance services. iMonitor respects the privacy of your User Information and will treat User Information in accordance with the Privacy Policy. You have the right to update your User Information, or if you would like to withdraw your consent to the collection, storage and use of your User Information, you may immediately cancel your use of the Services at any time as provided in Section 10 below.

<b>4. License Rights and Use Restrictions</b>
(a) Access and Use. Subject to the terms and conditions of this Agreement, any applicable limitations on the number of devices and payment of any applicable fees, iMonitor grants you a non-transferable, non-exclusive, right (without the right to sublicense) to access and use the Services as provided to you by iMonitor and solely for the purpose of controlling and monitoring your iMonitor System (the "Permitted Purpose").
(b) Certain Restrictions. Your use of the Services is subject to the following restrictions: you agree (i) not to license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Services; (ii) not to modify, make derivative works of, disassemble, reverse compile, or reverse engineer any part of the Services; (iii) not to access the Services in order to build a similar or competitive service, (iv) not to use the Services for any unlawful purpose, or for any purpose other than the Permitted Purpose; (v) that no part of the Services may be copied, reproduced, distributed, republished, downloaded, displayed, posted, or transmitted in any form or by any means; (vi) not to upload, transmit, or distribute any computer viruses, worms, or any software intended to damage or alter a computer or communication network, computer, handheld mobile device, data, the Website, the Services, the Hardware, the Software, or any other system, device or property; (vii) not to interfere with, disrupt, or attempt to gain unauthorized access to, the servers or networks connected to the Website or the Services, or violate the regulations, policies, or procedures of such networks; (viii) not to access (or attempt to access) any of the Services by means other than through the interface that is provided by iMonitor; and (ix) not to remove, obscure or alter any proprietary rights notices (including copyrights and trademark notices) which may be contained in or displayed in connection with the Website or the Services.
(c) IN ADDITION, IN NO EVENT DOES iMonitor AUTHORIZE YOU OR ANYONE ELSE TO USE THE SERVICES WHERE THE FAILURE OF THE SERVICES TO PERFORM CAN REASONABLY BE EXPECTED TO RESULT IN SIGNIFICANT PHYSICAL INJURY, OR IN LOSS OR PROPERTY, OR IN LOSS OF LIFE. ANY SUCH USE IS ENTIRELY AT YOUR OWN RISK, AND YOU AGREE TO INDEMNIFY AND HOLD iMonitor HARMLESS FROM ANY AND ALL CLAIMS OR LOSSES RELATING TO SUCH UNAUTHORIZED USE.
(d) iMonitor reserves the right, at any time, to modify, suspend, or discontinue the Services or any part thereof, with or without notice. You agree that iMonitor will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Services or any part thereof.

<b>5. Third-Party Content</b>
The Services may give you the ability to access content, such as music or video services, television or other material, controlled or provided by third parties ("Third-Party Content"). You understand and acknowledge that: (a) Third-Party Content remains the property of the applicable third parties, who have the sole right to determine your rights to use such content; (b) iMonitor is not responsible for, and has no editorial control over, any Third-Party Content, and iMonitor does not sponsor or endorse any such content; and (c) iMonitor has no control over the distribution of Third-Party Content. You agree that iMonitor will have no liability to you or to any third parties, including without limitation to anyone else who uses your iMonitor System, related to or arising out of to any Third-Party Content. You also agree that neither the Services will not be used to illegally copy, display or otherwise make use of Third-Party Content without authorization from the appropriate rights holder or in violation of applicable law. Unauthorized copying or distribution of copyrighted or trademarks may constitute an infringement of the copyright or trademark holders' intellectual property rights. In addition, steps intended to defeat or bypass security measures designed to prevent infringement of the intellectual property rights of others may be illegal under Government of India law or comparable foreign laws. iMonitor reserves the right to terminate your right to access and use the Services and delete your account if iMonitor believes in good faith that you have used the Services or your iMonitor System to infringe upon the intellectual property rights of others.

<b>6. Subscription Fees and Payment; Taxes</b>

(a) Subscription Fees. Access to the Services is provided on a subscription basis and requires the payment of a subscription fee ("Subscription Fee"). You agree to pay any applicable Subscription Fee charged by iMonitor in advance. Initial subscriptions are for a period of one (1) year following the activation of your account. If for any reason you need to reactivate a subscription, you may be charged a reactivation fee. If you register for the Services under a promotional Subscription Fee, some additional restrictions and limitations may apply.
(b) Payment. Access to your account will not be permitted until iMonitor has verified that the payment is accurate and that your account is in good standing. iMonitor reserves the right to suspend or terminate your access to the Services without notifying you upon rejection of any payment or if your payment channel (or its agent or affiliate) seeks return of payments previously made to iMonitor for the Services. Such rights are in addition to and not in lieu of any other legal right or remedies available to iMonitor. iMonitor reserves the right to refer your account to a third party for collection in the event of an ongoing default, and you agree to reimburse iMonitor for any costs incurred by iMonitor in the collection of amounts that are past due, including for any reasonable attorneys' fees and court costs.
(c) Changes in Subscription Fees. iMonitor may, in its sole discretion, change fees from time to time and charge additional fees for any features and functionalities that are not a part of the initial Services covered by a Subscription Fee. iMonitor will use commercially reasonable efforts to notify you (by email or such other method reasonably selected by iMonitor) thirty (30) days in advance of any fee changes or new fees.
(d) Taxes. The amounts payable by you to iMonitor here under are exclusive of any applicable sales, use, value added, excise or similar taxes that may apply to the transactions contemplated here under. Any such taxes shall be your responsibility and you agree to pay to iMonitor any such taxes that iMonitor is required to collect under applicable law.

<b>7. Internet Service Provider Charges</b>
Access to and use of the Services requires the use of, and you are responsible for, an always-on broadband Internet connection. iMonitor is not responsible for and does not make any assurances about the availability or functionality of any broadband Internet connection. Network protection for your Internet connection is strongly advised to protect your iMonitor System against viruses and other types of harm. You are responsible for any service charges for your Internet connection incurred as a result of using or accessing the Website and/or the Services and acknowledge and agree that you shall be solely responsible for all disputes with any Internet service provider related to the same.
<b>8. Certain of Your Representations and Warranties to iMonitor</b>
You represent and warrant to iMonitor that: (a) you are at least eighteen (18) years of age and are competent, and have the authority, to enter into this Agreement; (b) you have provided or will provide iMonitor with User Information that is correct and complete; (c) you will not use the Services in violation of any applicable laws, regulations, or ordinances or for any illegal or unauthorized activities; (d) you take full responsibility for the actions of anyone to whom you disclose your password or login ID or whom you otherwise allow to access your account; and (e) you will never circumvent, compromise, nor attempt to circumvent or compromise any iMonitor security measures in connection with the Services.

<b>9. Dealers Are Independent Contractors, Not Agents of iMonitor</b>
You are required to purchase your iMonitor System from an authorized iMonitor dealer or distributor ("Dealer") in your area of your choice. While such Dealers receive training regarding iMonitor Systems, Dealers are independent contractors and service providers, and not employees or agents of iMonitor. Accordingly, (i) iMonitor makes no representations or warranties with respect to Dealers or their services and is in no way responsible for their acts or omissions, and (ii) Dealers have no right to bind iMonitor legally or otherwise make commitments on behalf of iMonitor. You are solely responsible to select a competent Dealer that meets your expectations. Such Dealer may offer additional installation, configuration or ongoing maintenance services. 
Any disputes, which may arise between you and your Dealer, are to be resolved between you and your Dealer.

<b>10. Term and Termination</b>
These Terms will remain in full force and effect so long as you continue to use or access the Website and/or the Services, or until terminated in accordance with the provisions of this section. You may terminate your account and your right to use the Services for any reason, at any time. Your access to the Services and your account will be terminated upon your written or emailed request and any unused Subscription Fees that you have paid are nonrefundable. At any time iMonitor may suspend or terminate your rights to use the Services, if iMonitor in good faith believes that you have used the Services in violation of this Agreement. If you transfer or assign your iMonitor System or any portion thereof to a new owner, your right to use the Services with respect to such products automatically terminates, and the new owner will have no right to use the Services under your account (as described below), and will be required to register for a separate account with iMonitor . In addition, iMonitor reserves the right to terminate your Services account and this Agreement for any reason or no reason, if iMonitor gives you at least thirty (30) days advance notice of such termination. Upon any such termination of your account by iMonitor , you will remain obligated to pay all outstanding fees and charges relating to your use of the Services prior to termination, but iMonitor will return any unused Subscription Fees that you have paid if Your account is terminated for any reason other than Your breach of this Agreement.

<b>11. Ownership</b>
You acknowledge that all right title and interest in and to the Services, including all intellectual property rights therein and thereto, remain the exclusive property of iMonitor and its licensors, and this Agreement grants to you no right or interest therein other than the limited rights expressly set forth herein, and iMonitor and its licensors and suppliers reserve all rights not granted in this Agreement.

<b>12. Your Indemnification of iMonitor</b>
You agree to defend, indemnify and hold harmless iMonitor, and its officers, directors, employees, consultants, agents, and other representatives, from and against any and all suits, claims, actions, proceedings, damages, demands, injuries, liabilities, losses, costs and expenses (including reasonable attorneys' fees), arising from or related to: (a) your negligence or willful misconduct; (b) your use of the Services; (c) your breach of any of your representations, warranties, obligations, or covenants in this Agreement; and (d) your use of Third-Party Content.

<b>13. Warranty Disclaimers</b>
(a) THE WEBSITE AND THE SERVICES ARE PROVIDED FOR YOUR CONVENIENCE, ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTY OF ANY KIND, AND iMonitor AND ITS LICENSORS AND SUPPLIERS EXPRESSLY DISCLAIM, TO THE GREATEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.
(b) WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, iMonitor AND ITS LICENSORS AND SUPPLIERS MAKE NO WARRANTY THAT DEFECTS WILL BE CORRECTED OR THAT THE WEBSITE OR THE SERVICES: (I) WILL MEET YOUR REQUIREMENTS; (II) WILL BE COMPATIBLE WITH YOUR COMPUTER OR MOBILE DEVICE; (III) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (IV) WILL BE ACCURATE OR RELIABLE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM iMonitor, ANY DEALER OR THROUGH THE WEBSITE OR THE SERVICES SHALL CREATE ANY WARRANTY WITH RESPECT TO THE WEBSITE OR THE SERVICES. FURTHER, iMonitor DOES NOT WARRANT THAT THE WEBSITE OR THE SERVICES OR THE iMonitor SERVERS THAT PROVIDE YOU WITH DATA AND CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU ASSUME THE ENTIRE RISK WITH RESPECT TO YOUR USE OF THE SERVICES. FURTHERMORE, iMonitor MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO ANY PROFESSIONAL SERVICES PERFORMED BY ANY iMonitor DEALERS.

<b>14. Exclusions</b>
Some jurisdictions do not allow the exclusion of implied warranties or the exclusion or limitation of incidental or consequential damages, so the above limitations or exclusions may not apply to you. This Agreement gives you specific legal rights, and you may also have other rights, which vary from jurisdiction to jurisdiction. The disclaimers, exclusions, and limitations of liability under this Agreement will not apply to the extent prohibited by applicable law.

<b>15. Forward-Looking Statements</b>
This website contains express or implied forward-looking statements, which are based on current expectations of management. These statements relate to, among other things, our expectations regarding management's plans, objectives, and strategies. These statements are neither promises nor guarantees, but are subject to a variety of risks and uncertainties, many of which are beyond our control, and which could cause actual results to differ materially from those contemplated in these forward-looking statements. In particular, the risks and uncertainties include, among other things: changing market conditions, the introduction of new competitive products, challenges related to changing technologies, supply chain disruptions, unanticipated defects or deficiencies in the hardware, software or related services or changes in governmental regulations or requirements. iMonitor assumes no obligation to update any forward-looking statements contained on the Website in the event of changing circumstances or otherwise, and such statements are current only as of the date they are made.

<b>16.Updates</b>
iMonitor may make improvements and/or changes to this Website at any time. Although we attempt to periodically update information on this website, the information, materials and services provided on or through this Website may occasionally be inaccurate, incomplete or out of date. iMonitor does not have a duty to update information contained in this Website, and iMonitor will not be liable for any failure to update such information. We make no representation as to the completeness, accuracy or currentness of any information on this Website, and we undertake no obligation to update or revise the information contained on this Website, whether as a result of new information, future events or circumstances or otherwise. It is your responsibility to verify any information contained in this Website before relying upon it.

<b>17.Miscellaneous</b>
This Agreement represents the entire agreement between you and iMonitor with respect to your use, and iMonitor's provision, of the Website and the Services, and its terms supersede and replace any prior or contemporaneous written or oral statements by iMonitor or its representatives, dealers, or resellers. If any provision of this Agreement is held by a court to be invalid or unenforceable under applicable law, such provision will be deemed modified to the extent necessary to render such provision valid and enforceable, and the other provisions of this Agreement will remain in full force and effect. The official text of this Agreement or notice submitted here under shall be in English. In the event of any dispute concerning the construction or meaning of this Agreement, reference shall be made only to this Agreement as written in English and not to any translation into another language, and this Agreement will not be construed against the drafting party. You may not amend this Agreement except in a writing signed by iMonitor. You may not assign, sublicense or transfer any of your rights and obligations under this Agreement to a third party without iMonitor's prior written consent. Any attempted assignment, sublicense, or transfer without the prior written consent of iMonitor shall be null and void. iMonitor's failure to enforce any of the terms of the terms and conditions of this Agreement shall not constitute a waiver or relinquishment of iMonitor's right to do so at any time. Sections 4(b), 6, 10, and 12 - 17 shall survive any termination or expiration of this Agreement.
Copyright 2017 iMonitor Solutions India Private Limited. All rights reserved. All trademarks, logos, trade names and service marks ("Marks") displayed on the Website or the Services are the property of iMonitor or of their respective holders. You are not permitted to use any of the Marks without the applicable prior written consent of iMonitor or such respective holders. iMonitor reserves the right to alter product and services offerings, specifications, and pricing at any time without notice, and is not responsible for typographical or graphical errors that may appear in this or in related documents.
</pre>
</div>
</body>
</html>